- name: "Batch tasks"
  become: true
  gather_facts: false
  hosts: all
  tasks:
  # Basic User and Docker Installation
    -
      name: "Creating User '{{username}}'"
      ansible.builtin.user:
        groups: "sudo"
        name: "{{username}}"
        password: "{{password}}"
        state: present
        system: false
        append: yes
        home: /home/({username})
        shell: /bin/bash
    -
      name: "Docker Dependencies"
      apt:
        update_cache: true
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    -
      name: "Docker GPG Key"
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
    -
      name: "Docker Repository"
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{version}} stable"
    -
      name: "Docker Packages"
      apt:
        update-cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    -
      name: "PIP for Python"
      apt:
        name: python3-pip
        state: latest
        update_cache: true
    -
      name: "Docker SDK for Python"
      pip:
        name:
          - docker
          - docker-compose
        state: latest

  vars:
   username: "dio"
   password: "$6$L3v4luDCaPkDYBxr$2Bw/yFCfC07bimUn6vsOSLmpwGsPSHjCLfF5RFLn/n.7XFmn2A5OY9rcnG8iQ8RUDhhMlqRnacc29uBmHXENR1"
   version: "focal"
