- become: true
  gather_facts: false
  hosts: appserver
  tasks:
  - name: "Git Clone for be-dumbmerch on {{ ansible_user }} homedir"
    ansible.builtin.git:
      repo: 'https://github.com/demo-dumbways/be-dumbmerch'
      dest: /home/{{ ansible_user }}/git/be-dumbmerch
      clone: yes
      update: yes
    become_user: "{{ ansible_user }}"
  - name: "Git Clone for fe-dumbmerch on {{ ansible_user }} homedir"
    ansible.builtin.git:
      repo: 'https://github.com/demo-dumbways/fe-dumbmerch'
      dest: /home/{{ ansible_user }}/git/fe-dumbmerch
      clone: yes
      update: yes
    become_user: "{{ ansible_user }}"
  - name: "Prometheus Data for Docker Volume"
    file:
      path: "/opt/data/prometheus"
      state: directory
      mode: '0777'
  - name: "Grafana Data for Docker Volume"
    file:
      path: "/opt/data/grafana"
      state: directory
      mode: '0777'
  - name: "Prometheus Config"
    copy:
      dest: "/tmp/prometheus.yml"
      content: |
        global:
          scrape_interval: 30s

        scrape_configs:
          - job_name: 'node'
            scrape_interval: 10s
            static_configs:
              - targets: ['node1.dio.studentdumbways.my.id','node2.dio.studentdumbways.my.id']

          - job_name: 'nginx'
            scrape_interval: 10s
            static_configs:
              - targets: ['node1.dio.studentdumbways.my.id:9113']
  - name: "Install Grafana and Friends"
    community.docker.docker_compose:
      project_name: monitoring
      definition:
        version: '2'
        services:
          node-exporter:
            image: bitnami/node-exporter
            ports:
              - 9100:9100
          prometheus:
            image: prom/prometheus
            ports:
              - 9090:9090
            volumes:
              - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
              - /opt/data/prometheus:/prometheus
            depends_on:
              - node-exporter
          grafana:
            image: grafana/grafana
            ports:
              - 3000:3000
            volumes:
              - /opt/data/grafana:/var/lib/grafana
            depends_on:
              - prometheus
      state: present
    register: output
